### ISSUE TITLE
thrift2pyi.exceptions.Thrift2pyiException: do not type support 18

### ISSUE THREAD

**Issue by buptwanglong** [nhywieza/thrift2pyi#13]
Traceback (most recent call last):
  File "/Users/wanglong/Library/Caches/pypoetry/virtualenvs/event-data-tmScpDmQ-py3.7/bin/thrift2pyi", line 8, in <module>
    sys.exit(main())
  File "/Users/wanglong/Library/Caches/pypoetry/virtualenvs/event-data-tmScpDmQ-py3.7/lib/python3.7/site-packages/thrift2pyi/main.py", line 20, in main
    Thrift2pyi(thrift, args.prefix, args.out).output()
  File "/Users/wanglong/Library/Caches/pypoetry/virtualenvs/event-data-tmScpDmQ-py3.7/lib/python3.7/site-packages/thrift2pyi/convert.py", line 265, in output
    self._thrift2pyi()
  File "/Users/wanglong/Library/Caches/pypoetry/virtualenvs/event-data-tmScpDmQ-py3.7/lib/python3.7/site-packages/thrift2pyi/convert.py", line 257, in _thrift2pyi
    self._structs2pyi()
  File "/Users/wanglong/Library/Caches/pypoetry/virtualenvs/event-data-tmScpDmQ-py3.7/lib/python3.7/site-packages/thrift2pyi/convert.py", line 142, in _structs2pyi
    self.pyi.structs.append(self._struct2pyi(struct))
  File "/Users/wanglong/Library/Caches/pypoetry/virtualenvs/event-data-tmScpDmQ-py3.7/lib/python3.7/site-packages/thrift2pyi/convert.py", line 136, in _struct2pyi
    p_init.params, p_struct.annotations = self._spec2params(struct.default_spec, struct.thrift_spec)
  File "/Users/wanglong/Library/Caches/pypoetry/virtualenvs/event-data-tmScpDmQ-py3.7/lib/python3.7/site-packages/thrift2pyi/convert.py", line 122, in _spec2params
    p_annotation.type = self._spec2type(spec)
  File "/Users/wanglong/Library/Caches/pypoetry/virtualenvs/event-data-tmScpDmQ-py3.7/lib/python3.7/site-packages/thrift2pyi/convert.py", line 91, in _spec2type
    return self._get_type(spec[0])
  File "/Users/wanglong/Library/Caches/pypoetry/virtualenvs/event-data-tmScpDmQ-py3.7/lib/python3.7/site-packages/thrift2pyi/convert.py", line 64, in _get_type
    raise Thrift2pyiException("do not type support %s" % thrift_type)
thrift2pyi.exceptions.Thrift2pyiException: do not type support 18

-----------------------
binary 类型不支持么，最新版 1.0.4

**Comment by nhywieza** [comment]
刚加上
