### ISSUE TITLE
thrift2pyi.exceptions.Thrift2pyiException: do not type support 18  过不了呢

### ISSUE THREAD

**Issue by qing-714** [nhywieza/thrift2pyi#14]
Traceback (most recent call last):
  File "/Users/qingfan/all_code/python_workspace/byte/life_order_ate/ate_venv/bin/thrift2pyi", line 8, in <module>
    sys.exit(main())
  File "/Users/qingfan/all_code/python_workspace/byte/life_order_ate/ate_venv/lib/python3.9/site-packages/thrift2pyi/main.py", line 20, in main
    Thrift2pyi(thrift, args.prefix, args.out).output()
  File "/Users/qingfan/all_code/python_workspace/byte/life_order_ate/ate_venv/lib/python3.9/site-packages/thrift2pyi/convert.py", line 267, in output
    self._thrift2pyi()
  File "/Users/qingfan/all_code/python_workspace/byte/life_order_ate/ate_venv/lib/python3.9/site-packages/thrift2pyi/convert.py", line 258, in _thrift2pyi
    self._scan_includes()
  File "/Users/qingfan/all_code/python_workspace/byte/life_order_ate/ate_venv/lib/python3.9/site-packages/thrift2pyi/convert.py", line 167, in _scan_includes
    Thrift2pyi(include.__thrift_file__, self.prefix, self.out).output()
  File "/Users/qingfan/all_code/python_workspace/byte/life_order_ate/ate_venv/lib/python3.9/site-packages/thrift2pyi/convert.py", line 267, in output
    self._thrift2pyi()
  File "/Users/qingfan/all_code/python_workspace/byte/life_order_ate/ate_venv/lib/python3.9/site-packages/thrift2pyi/convert.py", line 258, in _thrift2pyi
    self._scan_includes()
  File "/Users/qingfan/all_code/python_workspace/byte/life_order_ate/ate_venv/lib/python3.9/site-packages/thrift2pyi/convert.py", line 167, in _scan_includes
    Thrift2pyi(include.__thrift_file__, self.prefix, self.out).output()
  File "/Users/qingfan/all_code/python_workspace/byte/life_order_ate/ate_venv/lib/python3.9/site-packages/thrift2pyi/convert.py", line 267, in output
    self._thrift2pyi()
  File "/Users/qingfan/all_code/python_workspace/byte/life_order_ate/ate_venv/lib/python3.9/site-packages/thrift2pyi/convert.py", line 258, in _thrift2pyi
    self._scan_includes()
  File "/Users/qingfan/all_code/python_workspace/byte/life_order_ate/ate_venv/lib/python3.9/site-packages/thrift2pyi/convert.py", line 167, in _scan_includes
    Thrift2pyi(include.__thrift_file__, self.prefix, self.out).output()
  File "/Users/qingfan/all_code/python_workspace/byte/life_order_ate/ate_venv/lib/python3.9/site-packages/thrift2pyi/convert.py", line 267, in output
    self._thrift2pyi()
  File "/Users/qingfan/all_code/python_workspace/byte/life_order_ate/ate_venv/lib/python3.9/site-packages/thrift2pyi/convert.py", line 258, in _thrift2pyi
    self._scan_includes()
  File "/Users/qingfan/all_code/python_workspace/byte/life_order_ate/ate_venv/lib/python3.9/site-packages/thrift2pyi/convert.py", line 167, in _scan_includes
    Thrift2pyi(include.__thrift_file__, self.prefix, self.out).output()
  File "/Users/qingfan/all_code/python_workspace/byte/life_order_ate/ate_venv/lib/python3.9/site-packages/thrift2pyi/convert.py", line 267, in output
    self._thrift2pyi()
  File "/Users/qingfan/all_code/python_workspace/byte/life_order_ate/ate_venv/lib/python3.9/site-packages/thrift2pyi/convert.py", line 259, in _thrift2pyi
    self._structs2pyi()
  File "/Users/qingfan/all_code/python_workspace/byte/life_order_ate/ate_venv/lib/python3.9/site-packages/thrift2pyi/convert.py", line 144, in _structs2pyi
    self.pyi.structs.append(self._struct2pyi(struct))
  File "/Users/qingfan/all_code/python_workspace/byte/life_order_ate/ate_venv/lib/python3.9/site-packages/thrift2pyi/convert.py", line 138, in _struct2pyi
    p_init.params, p_struct.annotations = self._spec2params(struct.default_spec, struct.thrift_spec)
  File "/Users/qingfan/all_code/python_workspace/byte/life_order_ate/ate_venv/lib/python3.9/site-packages/thrift2pyi/convert.py", line 124, in _spec2params
    p_annotation.type = self._spec2type(spec)
  File "/Users/qingfan/all_code/python_workspace/byte/life_order_ate/ate_venv/lib/python3.9/site-packages/thrift2pyi/convert.py", line 95, in _spec2type
    return self._get_type((spec[0], spec[2]))
  File "/Users/qingfan/all_code/python_workspace/byte/life_order_ate/ate_venv/lib/python3.9/site-packages/thrift2pyi/convert.py", line 80, in _get_type
    return "Dict[%s,%s]" % (self._get_type(nest[0]), self._get_type(nest[1]))
  File "/Users/qingfan/all_code/python_workspace/byte/life_order_ate/ate_venv/lib/python3.9/site-packages/thrift2pyi/convert.py", line 64, in _get_type
    raise Thrift2pyiException("do not type support %s" % thrift_type)
thrift2pyi.exceptions.Thrift2pyiException: do not type support 18

**Comment by qing-714** [comment]
我也是最新版 1.0.4
